application-auto-scaling_RegisterScalableTarget:
  languages:
    Java:
      versions:
        - sdk_version: 2
          github: javav2/example_code/appautoscale
          excerpts:
            - description:
              snippet_tags:
                - appautoscale.java2.enable.main
  services:
    application-auto-scaling: {RegisterScalableTarget}
application-auto-scaling_DeleteScalingPolicy:
  languages:
    Java:
      versions:
        - sdk_version: 2
          github: javav2/example_code/appautoscale
          excerpts:
            - description:
              snippet_tags:
                - appautoscale.java2.disable.main
  services:
    application-auto-scaling: {DeleteScalingPolicy}
application-auto-scaling_DescribeScalingPolicies:
  languages:
    Rust:
      versions:
        - sdk_version: 1
          github: rustv1/examples/applicationautoscaling
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - applicationautoscaling.rust.describe-scaling-policies
  services:
    application-auto-scaling: {DescribeScalingPolicies}
